### PR TITLE
compiled for mac on travis

### PR DESCRIPTION
**Pull request by mkinney**
Thanks for the great example for cross compiling. 

Don't forget to revert the travis line in README.md.

### CODE REVIEW

**Comment by zer0main** [comment]
Thank you! 👍 I have some thoughts on this pull request.
- Please delete commented code from `windows/requirements.sh` and `linux/requirements.sh`
- `apt-get update` in `before_install` section of `.travis.yml` is needed because travis worker can have outdated package list. In this case, an attempt to install such a package results in `404 Not found` error.
- Remove extra line from Game.hpp

**Comment by mkinney** [comment]
- removed commented steps
- cannot have apt-get command on mac build, but I made sure it was the first step in the requirements for linux and windows
- removed extra line

**Comment by zer0main** [comment]
Thanks. And why do we need to remove `/var/lib/apt/lists`? [ This error](https://travis-ci.org/mkinney/battleship/jobs/124110389) was caused by gpg server fault.

**Comment by mkinney** [comment]
I had that in there because I was trying to get 'apt-get upgrade' working. The error is because there was no 'sudo' command in the front of the command. This removal is not really needed, so I just pushed one more change to remove it.

Let me know if you have any other questions.

**Pull request merged**
